export const skipData = [
    {
        id: 11554,
        size: 4,
        hire_period_days: 14,
        price_before_vat: 311,
        vat: 20,
        allowed_on_road: true,
    },
    {
        id: 11555,
        size: 6,
        hire_period_days: 14,
        price_before_vat: 342,
        vat: 20,
        allowed_on_road: true,
    },
    {
        id: 11556,
        size: 8,
        hire_period_days: 14,
        price_before_vat: 420,
        vat: 20,
        allowed_on_road: true,
    },
    {
        id: 11557,
        size: 10,
        hire_period_days: 14,
        price_before_vat: 448,
        vat: 20,
        allowed_on_road: false,
    },
    {
        id: 11558,
        size: 12,
        hire_period_days: 14,
        price_before_vat: 491,
        vat: 20,
        allowed_on_road: false,
    },
    {
        id: 11559,
        size: 14,
        hire_period_days: 14,
        price_before_vat: 527,
        vat: 20,
        allowed_on_road: false,
    },
    {
        id: 11560,
        size: 16,
        hire_period_days: 14,
        price_before_vat: 556,
        vat: 20,
        allowed_on_road: false,
    },
    {
        id: 11561,
        size: 20,
        hire_period_days: 14,
        price_before_vat: 944,
        vat: 20,
        allowed_on_road: false,
    },
    {
        id: 11562,
        size: 40,
        hire_period_days: 14,
        price_before_vat: 944,
        vat: 20,
        allowed_on_road: false,
    },
];
